kkos/oniguruma

regint.h

Fixes following compilationg warning related to https://github.com/kkos/oniguruma/commit/b0734c30a5d973776fe7fd93e611f3a93652c41a
`warning C4133: 'function' : incompatible types - from 'hash_data_type *' to 'st_data_t *'`

Fix a compilation warning under windows

---

src/unicode.c

Some local variable is not declared at the top of scope.
This cause compile error in non C99 compiler. e.g. Visual Studio 2005.

declare variables at the top of scope

---

src/regcomp.c
src/regerror.c
src/regparse.c

Imported three patches for UTF-16/32 from Onigmo.
* `/[\x{0}-X]/i` doesn't match properly when UTF-16/32 is used.
* `/[a-c#]+\W/ =~ "def#"` fails when encoding is UTF-16/32
* When encoding is UTF-16LE/32LE, warning message with '/' or '\\' are not shown properly.
#36 might be fixed by them.

Fix UTF-16/32 problems

---

doc/API
doc/API.ja
src/oniguruma.h
src/regerror.c
src/regint.h
src/regparse.c
src/regparse.h

Oniguruma's parser uses recursion, so it causes stack overflow when parsing
deeply nested capture groups. E.g.:
x2("(" * 32767 + "a" + ")" * 32767, "a", 0, 1)
This patch sets a limit for this.
The default value is defined in regint.h:
* DEFAULT_PARSE_DEPTH_LIMIT (Currently 4096)
Also add two APIs to support this:
* onig_get_parse_depth_limit
* onig_set_parse_depth_limit
Ported from k-takata/Onigmo#68 .

Deeply nested capture groups cause stack overflow

---

src/regcomp.c
src/regexec.c

Fix following patterns:
* `/(?<=a).*b/ =~ 'aab'`
* `/(?!a).*b/ =~ 'ab'`
Ported from Onigmo. (k-takata/Onigmo#44)

Fix .* optimization

---

src/regexec.c

`"こんにちは" =~ /\n?\z/` didn't match.
see:
http://bugs.ruby-lang.org/issues/8210
http://stackoverflow.com/a/15885857/925913
Ported from k-takata/Onigmo#16 .

fix problem with optimization of \z

---

src/regcomp.c

After matching `/(\(((?:[^(]|\g<1>)*)\))/ =~ "(abc)(abc)"`,
`\2` captures wrong position.
A capture group inside another capture group should be also handled as
if it is called, when the outer group is called.
(I'm not sure both `IN_CALL` and `IN_RECCALL` are needed or not.)
Originally reported at k-takata/Onigmo#48 .

Fix illegal capture after recursive call

---

src/regparse.c

It did not work as the comment said.
This was originally fixed by Ruby r37175.

[0-9-a] was not allowed as [0-9\-a]

---

src/regexec.c

xmemcpy in stack_double() is using the size of the newly doubled stack as the size parameter. This could result in reading past the current size of the memory pointed to by "base_alloc" during copy and accessing invalid memory.

Fix size in xmemcpy in stack_double

---

doc/FAQ

- Correct "lognest" => "longest"
- Add the article "the" to "execute longest match"
- Change "mailing list about Oniguruma" to "mailing list for Oniguruma" in the interest of more natural English

Correct spelling and grammar in FAQ (English)

---

make_win32.bat
make_win64.bat
src/Makefile.windows

The current windows NMAKE makefile system produces build artifacts in a fixed directory structure in the source directory. This pull requeqest ports [changes made in the `rust-onig` project](https://github.com/rust-onig/rust-onig/issues/49) to allow out-of-tree builds. This functionality was useful in `rust-onig` to allow the build artifacts and finished product to be placed in the same intermediate build directory as compiled Rust assets.

Out of tree windows builds

---

src/config.h.win32
src/config.h.win64

Hello, the definitions of the `HAVE_ST_RDEV` and `HAVE_STRUCT_STAT_ST_RDEV` would provide checks for the members of the stat struct. Since the st_rdev member is not used in this code these checks can be simplified by removal.
Thanks for checking this out or considering merging it.

Remove unused defines from Windows configure file

---

README_japanese

Hello,
opening the `README_japanese` file on some editors causes issues and it automatically opens it in UTF-8 so characters are not shown properly. This patch converts the EUC-JP encoding to UTF-8 for convenience of seeing it properly.
Thank you for considering checking this out or merging it.

Convert README_japanese to UTF-8

---

configure.ac

Hello,
Autoconf made several macros obsolete including the `AC_TRY_COMPILE` in 2001 in version 2.50:
- http://git.savannah.gnu.org/cgit/autoconf.git/tree/ChangeLog.2
- http://git.savannah.gnu.org/cgit/autoconf.git/tree/ChangeLog.3
It should be replaced with the current `AC_COMPILE_IFELSE instead`.
Reference docs: 
- https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Obsolete-Macros.html
- https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/AC_005fFOO_005fIFELSE-vs-AC_005fTRY_005fFOO.html
Thank you for considering merging this or checking it out. In case of doubts or questions just ask...

Replace obsolete AC_TRY_COMPILE with AC_COMPILE_IFELSE

---

src/config.h.win32
src/config.h.win64

Hello,
The `RETSIGTYPE` defines the signal type. In K&R C, this could be `int` or `void`. Since C89 it is always `void`. Also the `RETSIGTYPE` is not used in current code.
This is usually also defined by the obsolete macro (AC_TYPE_SIGNAL](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Obsolete-Macros.html) in autoconf.
Thanks for considering merging this, or checking it out.

Remove unused RETSIGTYPE

---

src/config.h.win32
src/config.h.win64
src/config.h.windows.in

The `<float.h>` header file is part of the standard C89 headers [1] and
on current systems there is no need to do a manual check if header is
present anymore [2].
Build systems used to check for the presence of the header file and defined
the `HAVE_FLOAT_H` symbol.
Refs:
[1] https://port70.net/~nsz/c/c89/c89-draft.html#4.1.4
[2] http://git.savannah.gnu.org/cgit/autoconf.git/tree/lib/autoconf/headers.m4

Remove HAVE_FLOAT_H

---

configure.ac

Autoconf 2.59d (released in 2006) [1] started promoting several macros
as not relevant for newer systems anymore, including the `AC_FUNC_MEMCMP`.
On some old systems such as SunOS 4.1.3 (EOL in 2003) and NeXT x86
OpenStep (discontinued) the `memcmp` function wasn't present or it
didn't work properly. [2]
On current systems including at least Solaris 10+ this check is not
relevant anymore.
Refs:
[1] http://git.savannah.gnu.org/cgit/autoconf.git/tree/NEWS
[2] https://www.gnu.org/software/autoconf/manual/autoconf-2.69/autoconf.html

Remove AC_FUNC_MEMCMP

---

src/config.h.win32
src/config.h.win64
src/config.h.windows.in

The C89 standard and later defines the <string.h> header as part of the
standard headers [1]. Functions memcmp, memmove, strerror, strchr, strstr,
and others are all part of C89 and <string.h> header definition.
Some build systems used to define the presence of these functions via
HAVE_MEMCMP, HAVE_MEMMOVE, HAVE_STRERROR, HAVE_STRCHR, HAVE_STRSTR
symbols. These aren't used in oniguruma library anymore and can be
ommitted from the config files for windows systems.
[1]: https://port70.net/~nsz/c/c89/c89-draft.html#4.11

Remove unused old symbols for string.h functions

---

configure.ac

Autoconf 2.59d (released in 2006) [1] started promoting several macros
as not relevant for newer systems anymore, including the `AC_HEADER_TIME`.
This macro checks if both `<sys/time.h>` and `<time.h>` can be included
at the same time and defines the `TIME_WITH_SYS_TIME` and
`HAVE_SYS_TIME_H` symbols. On current system such check is not relevant
anymore because in case both headers are present both can be also
included at the same time.
This patch simplifies this checking.
Refs:
[1] http://git.savannah.gnu.org/cgit/autoconf.git/tree/NEWS
[2] https://www.gnu.org/software/autoconf/manual/autoconf-2.69/autoconf.html

Remove AC_HEADER_TIME

---

configure.ac

Autoconf 2.59d (released in 2006) [1] started promoting several macros
as not relevant for newer systems, including the `AC_C_CONST`.
The `const` keyword is used in C since C89. On old systems some compilers
lacked the `const` and this macro defined it to be empty. This check was
relevant on systems with compilers before C89 and on current systems it
can be omitted since ˙const` is always available. [2]
Refs:
[1] http://git.savannah.gnu.org/cgit/autoconf.git/tree/NEWS
[2] https://www.gnu.org/software/autoconf/manual/autoconf-2.69/autoconf.html

Remove AC_C_CONST

---

configure.ac

Autoconf 2.50 made several changes to macro calls. These include also
arguments passed to AC_OUTPUT macro. The upgrading chapter in Autoconf
documentation includes an example of using AC_OUTPUT with
AC_CONFIG_FILES and AC_CONFIG_COMMANDS:
- https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Obsolete-Macros.html
Systems out there should be well supported by now.
This patch was created with the help of autoupdate script:
autoupdate <file>
More info on where exactly this got deprecated:
- ftp://ftp.gnu.org/old-gnu/Manuals/autoconf-2.13/html_mono/autoconf.html
- ftp://ftp.auckland.ac.nz/pub/gnu/Manuals/autoconf-2.52/html_chapter/autoconf_15.html
- http://git.savannah.gnu.org/cgit/autoconf.git/tree/NEWS

Upgrade deprecated AC_OUTPUT macro call

---

CMakeLists.txt
configure.ac
src/config.h.cmake.in
src/config.h.win32
src/config.h.win64
src/config.h.windows.in

Autoconf 2.59d (released in 2006) [1] started promoting several macros
as not relevant for newer systems anymore, including the `AC_HEADER_STDC`.
This macro checks if given system has C89 compliant header files such
as <string.h>, <stdlib.h>, <stdarg.h>, <float.h>,... and defines the
`STDC_HEADERS` symbol [2]. Case is that current systems should be well
supported with at least C89 standard headers [3].
Given headers are still additionally checked with the `AC_PROG_CC`
macro, yet not needed anyway.
For cmake build system this applies similarly and the manual custom
check of the standard headers can be removed likewise.
Refs:
[1] http://git.savannah.gnu.org/cgit/autoconf.git/tree/NEWS
[2] https://www.gnu.org/software/autoconf/manual/autoconf-2.69/autoconf.html
[3] …

Remove obsolescent AC_HEADER_STDC

---

CMakeLists.txt
configure.ac
src/config.h.cmake.in
src/config.h.win32
src/config.h.win64
src/config.h.windows.in
src/regerror.c
src/regint.h

Hello,
The C89 standard and later defines the `<stdarg.h>` header as part of the standard headers [1] and on current systems it is always present.
Checking for presence and functionality of the `<stdarg.h>` header and variadic functions is not relevant anymore on current systems since this is always available.
Also Autoconf suggests doing this and relying on C89 or above [2] and [3].
As an alternative, outdated versions of POSIX defined the legacy header `<varargs.h>` [4].
This patch modernize the `<stdarg.h>` usage a bit.
Unused internal macro `va_init_list()` has been replaced with `va_start()`.
Checking if functions support prototypes is also not relevant anymore so the `HAVE_PROTOTYPES` symbol has been removed likewise.
Refs:
[1] https://port70.net/~nsz/c/c89/c89-draft.html#4.1.2
[2] …

Remove HAVE_PROTOTYPES and HAVE_STDARG_PROTOTYPES

---

src/config.h.win32
src/config.h.win64

Hello, the size of `size_t` is 4 bytes on 32bit Windows platforms and 8 bytes on 64bit Windows platforms. This patch defines the SIZEOF_SIZE_T symbols for both instead of using only 4 for both.
Ref:
- https://msdn.microsoft.com/en-us/library/3b2e7499.aspx
This patch has been done with help from the [PHP patch](https://github.com/php/php-src/blob/master/ext/mbstring/oniguruma.patch).
Thank you.

Set SIZEOF_SIZE_T for windows platforms

---

src/config.h.win32
src/config.h.win64
src/config.h.windows.in

The symbol HAVE_VSNPRINTF was once used for checks if vsnprintf can be used. Today this symbol is not used in oniguruma library anymore.
Thank you.

Remove unused HAVE_VSNPRINTF

---

CMakeLists.txt
configure.ac
src/config.h.cmake.in
src/config.h.win32
src/config.h.win64
src/config.h.windows.in

- SIZEOF_SHORT removed since it is not used
- second argument in the AC_CHECK_SIZEOF is not used anymore and can be
removed.

Sync AC_CHECK_SIZEOF

---

configure.ac

The Autoconf's default AS_HELP_STRING macro can properly format help
strings [1] so watching out if columns are aligned manually won't be
needed anymore.
These strings are visible in the configure --help output.
1: https://www.gnu.org/software/autoconf/manual/autoconf.html#Pretty-Help-Strings

Add AS_HELP_STRING

---

doc/SYNTAX.md

This hopefully fixes the `SYNTAX.md` documentation to match the behavior for escaped metacharacters.
(I completely forgot classic `grep` supported `\+` and `\(...\)`; I've been using `egrep` and `ag` for so long now that I can't remember classic grep's syntax!)
If you see anything else wrong, please let me know, and I'll be happy to fix it! :)

Fix syntax documentation for escaped metacharacters

---

sample/Makefile.am
src/Makefile.am
test/Makefile.am

Don't add -I$(includedir) to CPPFLAGS or cross-compilation will fail on:
libtool: compile: /home/fabrice/buildroot/output/host/bin/m68k-linux-gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE
-D_FILE_OFFSET_BITS=64 -Wall -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -fno-dwarf2-cfi-asm -Wl,-elf2flt -c regparse.c -o regparse.o
m68k-linux-gcc: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/include'
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

fix cross-compilation

---

CMakeLists.txt

I need static library oniguruma library with static runtime.
It can be generated by this PR.
cmake .. -G "Visual Studio 16 2019" -DBUILD_SHARED_LIBS=OFF -DMSVC_STATIC_RUNTIME=ON
And this PR replace set() and string(REGEX REPLACE).
with target_compile_options()

Add MSVC_STATIC_RUNTIME option in CMakeLists.txt

---

CMakeLists.txt
src/oniguruma.h

ONIG_EXTERN is defined wrong in windows static build.

Fix static build error

---

CMakeLists.txt
src/onigposix.h

1. https://github.com/kkos/oniguruma/blob/74319e1bc9a90d3d95647e2c24e6d6eb1d0a9813/src/oniguruma.h#L55
But `https://github.com/kkos/oniguruma/blob/master/src/onigposix.h` doesn't have this.
2.

fix static build

---

src/regexec.c
src/regint.h
src/regparse.c

This PR adds support for building oniguruma under the wasm32-unknown-unknown target with clang-8 or newer. There are two commits:
The oniguruma match engine has a direct threaded loop. The library detects whether to use this implementation by checking for a GCC compiler via the `__GNUC__` macro.
clang pretends to be GCC so threading is enabled for clang.
Until very recently, clang did not support threading ("computed gotos") under wasm targets. This is [fixed in trunk clang](https://bugs.llvm.org/show_bug.cgi?id=42498).
To unblock building wasm targets on older clang, add a macro that, when defined, disables threading regardless of the compiler.
This approach is [similar to the approach taken by mruby](https://github.com/mruby/mruby/blob/8ed15fd92e6d3ce7963db8c3162bdebee7b55e1b/src/vm.c#L9 …

Enable oniguruma to build on wasm32-unknown-unknown target

---

src/regcomp.c
src/regexec.c
src/regparse.c

This fixes some of the issues found by clang analyzer. 
Of these, `name_id` seems to be a legit bug — `goto callout_common_entry` skipped over its initialization.

Initialize potentially-uninitialized variables

---

src/regint.h
src/regparse.c

One is for signed shift overflow, the other for signed add overflow.

Fix two ubsan warnings

---

src/config.h.win32
src/config.h.win64
src/config.h.windows.in

As of commit e75db3c[1], regint.h won't build anymore, since <stdint.h>
is now required, but not included for MSVC due to `HAVE_STDINT_H` not
being defined.  Since <stdint.h> is available as of VS 2015 (and likely
even as of VS 2010), we define it unconditionally.
[1] <https://github.com/kkos/oniguruma/commit/e75db3c9b4b4f52a769c4ab494a25e3ce069944e>
---
Since the build error is a regression from Oniguruma 6.9.3, it would be great if it can be included in 6.9.4.

Fix MSVC build

---

src/regcomp.c

regcomp.c: In function ‘compile_bag_node’:
regcomp.c:1038:8: warning: ‘r’ may be used uninitialized in this function [-Wmaybe-uninitialized]
1038 |     if (r != 0) return r;
|        ^
regcomp.c:2082:7: note: ‘r’ was declared here
2082 |   int r;
|       ^

It make a warning.

---

CMakeLists.txt

Currently the SOVERSION is different when building with cmake than the
value used by autotools.
This adds the version information from autotools to cmake.
Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>
---
Current cmake-built library have no version information.  This PR makes cmake behavior equal to autotools.
I'm just not sure what to do about Windows builds.  It uses the VERSION property, but I'm not experienced with Windows enough to tell if the semantics are the same as the soname.  I believe libtool can build Windows libraries, and will use the same version scheme, so I'm leaving it the same as other systems.  Alternatively, the package version can be used instead, or we may leave it without version information.
I have tested this with Gentoo Linux.

Add SOVERSION info to library when using cmake

---

src/regparse.c

This fixes a php segfault, see
https://github.com/openwrt/packages/issues/12403
I traced it down with gdb
0xb6e37f70 in i_free_callout_name_entry (key=0x369040,
e=0x0, arg=0x37afe0) at oniguruma-6.9.5_rev1/src/regparse.c:1297

fix: check CalloutNameEntry for NULL before access

---

CMakeLists.txt
src/config.h.cmake.in

The library relies on them to define st_data_t, and hash_data_type
correctly.
Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

Have cmake set SIZEOF_LONG_LONG & SIZEOF_VOIDP

---

README.md
test/test_back.c
test/test_syntax.c
test/test_utf8.c
test/testc.c
test/testu.c
tis-ci/config.h
tis-ci/stub.c
tis-ci/test_back.config
tis-ci/test_regset.config
tis-ci/test_syntax.config
tis-ci/test_utf8.config
tis-ci/testc.config
tis-ci/testu.config
tis.config

Following up with [https://github.com/kkos/oniguruma/issues/208](https://github.com/kkos/oniguruma/issues/208), here is a Pull Request with the TIS CI configuration.
For you to make the most of TIS CI, I have split 6 of the oniguruma's large tests - `test_utf8.c`, `test_regset.c`, `test_syntax.c`, `testu.c`, `testc.c`, `test_back.c` - into 267 smaller TIS CI tests (for example, `test_utf8.c` has been split into 80 TIS CI tests):  
[https://ci.trust-in-soft.com/projects/jakub-zwolakowski/oniguruma/14](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/oniguruma/14)
Each TIS CI test is now small enough that it can be "explored" in case an issue has been detected in the code, via the **Explore** button. This helps a lot in pinpointing the problems and understanding where they come from. …

Initial TIS-CI configuration

---

test/testu.c

This PR is just to correct a mistake in the initial TIS CI configuration on my part.  
Sorry!... I've realized that something was wrong when I looked closer on my oniguruma verifications in TIS CI. Indeed, I've put the `#ifdef` directive in the wrong function in `testu.c` which causes problems with all the tests based on this file.
With this little patch this should be good!
(This has nothing to do with correcting the UBs, completely orthogonal topic.)

Fix the misplaced #ifdef in initial TIS CI config

---

tis-ci/test_back.config

I've noticed the last UB that you've uncovered and actually I've seen this before... This is a problem with TIS CI, the UB is misdiagnosed here, in reality this is a configuration error. The file defining the `OnigEncodingASCII` global (`src/ascii.c`) is not included in the configuration, so TIS CI has only the declaration to work with, and instead of complaining it goes through with the analysis.
Sorry! I'll report this as an issue internally.
This PR just adds the missing file.

fix TIS-CI config: add src/ascii.c to tis-ci/test_back.config files

---

sample/listcap.c

There is a small typo in sample/listcap.c.
Should read `history` rather than `hostory`.

docs: fix simple typo, hostory -> history

---

CMakeLists.txt

Old Visual Studio can't use inline but __inline.

replace inline with __inline when building with old MSVC

---

CMakeLists.txt

Make documentation optional and use doc sub directory
Add optional examples following the same directory structure
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

CMake: Make documentation and examples optional

---

CMakeLists.txt
onig-config.cmake.in
oniguruma.pc.cmake.in

In some platforms, liboniguruma could be installed in path/to/lib64 dir, but the oniguruma.pc file is installed in path/to/lib dir. And
the command pkg-config --libs oniguruma returns the wrong location

fix: use CMAKE_INSTALL_LIBDIR as install lib dir

---

CMakeLists.txt

Release tarball doesn't include sample/crnl.c

CMake: Fix INSTALL_EXAMPLES

---

CMakeLists.txt
test/CMakeLists.txt
windows/CMakeLists.txt

- Add BUILD_TEST option
- Add test/CMakelists.txt, windows/CMakelists.txt
Need /utf-8 option to build with MSVC.
And old MSVC does not support /utf-8 option.

Build tests with cmake+msvc

---

.gitignore

The files `*.trs` (Test ReSults) are generated files of `autoconf`. They are created by `make check` with `*.log`. I think we should prevent adding the test result files to git repository.

add *.trs to .gitignore

---

harnesses/base.c

Fixes a clang-18 error:
```
+ clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -o harnesses/fuzzer_syntax.o -I src -c -DSYNTAX_TEST harnesses/base.c
harnesses/base.c:204:42: error: parameter 'len' was not declared, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
204 | static unsigned int calc_retry_limit(sl, len)
|                                          ^
205 | {
harnesses/base.c:204:38: error: parameter 'sl' was not declared, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
204 | static unsigned int calc_retry_limit(sl, len)
|                                      ^
205 | { …
```

Update base.c: Add missing int types to calc_retry_limit

---

src/regint.h

Build on Solaris fails with:
src/regint.h:263:18: error: implicit declaration of function ‘alloca’ [-Wimplicit-function-declaration]

Fix Solaris GCC 14 build.

---

src/regint.h

Without this patch, trying to build Oniguruma with `-Werror=format-nonliteral` (which is the default in some environments, e.g. Xcode) results in the following:
```
regerror.c:363:40: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
363 |   n = xvsnprintf((char* )buf, bufsize, (const char* )fmt, args);
|                                        ^             ~~~
1 error generated.
```
By declaring `onig_snprintf_with_pattern()` as `printf()`-like, we tell the compiler to check the format string and arguments at the point where it is called instead.

Mark onig_snprintf_with_pattern() as printf()-like

---

sbom.cdx.json

Hi,
My name is Richard Hughes and I'm a developer at Red Hat. I'm the maintainer of fwupd and LVFS, and am trying to improve software supply chain security by encouraging OEMs, ODMs and IBVs to ship Software Bill of Materials with each firmware binary blob (SBOMs).
I'm working alongside lots of other companies proactively trying to do the right thing. The reason I've opened this pull request is because your project is either used in the *build process* of a firmware we care about (e.g. EDK II, or coreboot) or is built *into the firmware binary* itself. Although my personal focus is on firmware, the SBOM file is in CycloneDX format (one of the most popular industry standards) which makes it also useful when building containers or OS images too.
I would like to contribute this template SBOM …

Add a SBOM template in CycloneDX format
